SRC_DIR=src
OUT_DIR=out
SERVER_MAIN=server.ChatServer

all: compile run

compile:
	mkdir -p $(OUT_DIR)
	javac -d $(OUT_DIR) $(shell find $(SRC_DIR) -name "*.java")

run:
	java -cp $(OUT_DIR) $(SERVER_MAIN)