# Makefile.server (Linux/WSL)
JAVA = javac
JAVA_FLAGS = -cp .
SERVER_SRC = src/server
SERVER_CLASSES = bin/server

all: prepare server

prepare:
	mkdir -p $(SERVER_CLASSES)

server:
	$(JAVA) $(JAVA_FLAGS) -d $(SERVER_CLASSES) $(SERVER_SRC)/*.java

clean:
	rm -rf $(SERVER_CLASSES)

run:
	java -cp $(SERVER_CLASSES) server.ChatServer

.PHONY: all prepare server clean run