# Makefile.client (Windows)
JAVA = javac
JAVA_FLAGS = -cp .
CLIENT_SRC = src/client
CLIENT_CLASSES = bin/client

all: prepare client

prepare:
    if not exist "$(CLIENT_CLASSES)" mkdir "$(CLIENT_CLASSES)"

client:
    $(JAVA) $(JAVA_FLAGS) -d $(CLIENT_CLASSES) $(CLIENT_SRC)/*.java

clean:
    if exist "$(CLIENT_CLASSES)" rmdir /s /q "$(CLIENT_CLASSES)"

run:
    java -cp $(CLIENT_CLASSES) client.ClientMain

.PHONY: all prepare client clean run